### ISSUE TITLE
UnicodeDecodeError: 'cp932' codec can't decode byte 0x93

### ISSUE THREAD

**Issue by glass-ships** [spotipy-dev/spotipy#1168]
**Describe the bug**
Possibly Windows specific - trying to install latest commit results in:
```
  - Updating spotipy (2.24.0 db3fb9a -> 2.24.0 db3fb9a): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel

  Traceback (most recent call last):
    File "D:\dev\.libs\poetry\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "D:\dev\.libs\poetry\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "D:\dev\.libs\poetry\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\glass\AppData\Local\Temp\tmpd_98ypj1\.venv\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\glass\AppData\Local\Temp\tmpd_98ypj1\.venv\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
      self.run_setup()
    File "C:\Users\glass\AppData\Local\Temp\tmpd_98ypj1\.venv\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
      super().run_setup(setup_script=setup_script)
    File "C:\Users\glass\AppData\Local\Temp\tmpd_98ypj1\.venv\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
      exec(code, locals())
    File "<string>", line 4, in <module>
  UnicodeDecodeError: 'cp932' codec can't decode byte 0x93 in position 3199: illegal multibyte sequence
```

**Your code**
running `poetry install` on a project with `pyproject.toml` listing `spotipy = { git = "https://github.com/spotipy-dev/spotipy.git" }`

**Expected behavior**
Successful installation

**Output**
See above

**Environment:**
 - OS: Windows
 - Python version 3.12.7
 - spotipy version 2.24.0 db3fb9a
 - your IDE (if using any) VSCode

**Comment by dieser-niko** [comment]
Closing as there is no activity or reply from the author.
