### ISSUE TITLE
Exception on production enviroment

### ISSUE THREAD

**Issue by codertysmi** [spotipy-dev/spotipy#706]
**Describe the bug**
Python raise an error when using the package on production enviroment.

**Your code**
```python3
sp = spotipy.Spotify(auth_manager=SpotifyClientCredentials(client_id="example",
                                                            client_secret="example"))
```
Here is when it raise the error
`top_tracks = sp.playlist_tracks("someplaylist", limit=4)`

**Expected behavior**
Get songs information from playlists.

**Output**
```
web           | Traceback (most recent call last):
web           |   File "/code/api/views.py", line 461, in get
web           |     top_tracks = sp.playlist_tracks("someplaylist", limit=4)
web           |   File "/usr/local/lib/python3.8/site-packages/spotipy/client.py", line 643, in playlist_tracks
web           |     return self.playlist_items(playlist_id, fields, limit, offset,
web           |   File "/usr/local/lib/python3.8/site-packages/spotipy/client.py", line 667, in playlist_items
web           |     return self._get(
web           |   File "/usr/local/lib/python3.8/site-packages/spotipy/client.py", line 291, in _get
web           |     return self._internal_call("GET", url, payload, kwargs)
web           |   File "/usr/local/lib/python3.8/site-packages/spotipy/client.py", line 221, in _internal_call
web           |     headers = self._auth_headers()
web           |   File "/usr/local/lib/python3.8/site-packages/spotipy/client.py", line 212, in _auth_headers
web           |     token = self.auth_manager.get_access_token(as_dict=False)
web           |   File "/usr/local/lib/python3.8/site-packages/spotipy/oauth2.py", line 212, in get_access_token
web           |     token_info = self.cache_handler.get_cached_token()
web           |   File "/usr/local/lib/python3.8/site-packages/spotipy/cache_handler.py", line 67, in get_cached_token
web           |     token_info = json.loads(token_info_string)
web           |   File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
web           |     return _default_decoder.decode(s)
web           |   File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
web           |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
web           |   File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
web           |     raise JSONDecodeError("Expecting value", s, err.value) from None
web           | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Environment:**
- Python 3.8.5
- Docker, docker-compose
- ngnix
- Django
- Alpine
- Aws cloud

**Additional context**
When I use same code on localhost it works, perfectly.
Notes:
- I use https on the vps
- I'm able to make request to other apis inside the vps

**Comment by MeFaltaUnVerano21** [comment]
I tried with version 2.16.0 on my production enviroment and is working.

**Comment by Peter-Schorn** [comment]
This is definitely not a bug with spotipy. The error (on the very last line) indicates that the file which should contain the token info as JSON is empty. Delete that file and go through the authorization process again.

**Comment by dieser-niko** [comment]
@codertysmi is your issue solved or do you still need help?

**Comment by dieser-niko** [comment]
Closing as there is no activity or reply from the author.
