### ISSUE TITLE
Adding local files to a playlist

### ISSUE THREAD

**Issue by MelonHell** [spotipy-dev/spotipy#793]
I want to clone a playlist, normal tracks are added easily, but local files give an error

```python
def get_playlist_tracks(sp, playlist_id: str) -> list[str]:
	offset = 0
	track_uri_list = []
	while True:
		response = sp.playlist_items(
			playlist_id=playlist_id,
			offset=offset,
			fields='items,total',
			additional_types=['track']
		)

		if len(response['items']) == 0:
			break
		offset = offset + len(response['items'])

		for item in response['items']:
			track_uri_list.append(item['track']['uri'])
	return track_uri_list


def add_tracks_to_playlist(sp, playlist_id: str, tracks: list[str]):
	for i in range(0, len(tracks), 100):
		sp.playlist_add_items(playlist_id, tracks[i:i + 100])
		
		
tracks = get_playlist_tracks(sp, "7HhTH3iRJIhzhCEIT9uinN")
add_tracks_to_playlist(sp, "3PrVYE5UPJYkEzWxe7rwPF", tracks)
```

```
Expected id of type track but found type %D0%9D%D0%B5%D0%BF%D0%BE%D1%81%D1%82%D0%B5%D0%B6%D0%B8%D0%BC%D0%BE%D0%B5+%D0%B8+%D0%B2%D0%B5%D1%87%D0%BD%D0%BE%D0%B5 spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A1%D0%BC%D0%B5%D1%80%D1%82%D1%8C+%D0%90%D0%BC%D0%BE%D1%80%D0%B0%D0%BB%D0%B0.+Live+In+SayanCafe:%D0%9D%D0%B5%D0%BF%D0%BE%D1%81%D1%82%D0%B5%D0%B6%D0%B8%D0%BC%D0%BE%D0%B5+%D0%B8+%D0%B2%D0%B5%D1%87%D0%BD%D0%BE%D0%B5:211
Expected id of type track but found type %D0%9D%D0%B8%D0%BA%D0%BE%D0%B3%D0%B4%D0%B0 spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A1%D0%BC%D0%B5%D1%80%D1%82%D1%8C+%D0%90%D0%BC%D0%BE%D1%80%D0%B0%D0%BB%D0%B0.+Live+In+SayanCafe:%D0%9D%D0%B8%D0%BA%D0%BE%D0%B3%D0%B4%D0%B0:179
Expected id of type track but found type %D0%9F%D0%BE%D1%85%D0%BE%D1%82%D1%8C+%D0%BD%D0%B5+%D1%83%D0%BC%D0%B8%D1%80%D0%B0%D0%B5%D1%82 spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A1%D0%BC%D0%B5%D1%80%D1%82%D1%8C+%D0%90%D0%BC%D0%BE%D1%80%D0%B0%D0%BB%D0%B0.+Live+In+SayanCafe:%D0%9F%D0%BE%D1%85%D0%BE%D1%82%D1%8C+%D0%BD%D0%B5+%D1%83%D0%BC%D0%B8%D1%80%D0%B0%D0%B5%D1%82:228
Expected id of type track but found type %D0%A0%D0%B5%D0%B3%D0%BB%D0%B0%D0%BC%D0%B5%D0%BD%D1%82+%D1%85%D1%80%D0%BE%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B3%D0%BE+%D1%81%D1%87%D0%B0%D1%81%D1%82%D1%8C%D1%8F spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A1%D0%BC%D0%B5%D1%80%D1%82%D1%8C+%D0%90%D0%BC%D0%BE%D1%80%D0%B0%D0%BB%D0%B0.+Live+In+SayanCafe:%D0%A0%D0%B5%D0%B3%D0%BB%D0%B0%D0%BC%D0%B5%D0%BD%D1%82+%D1%85%D1%80%D0%BE%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B3%D0%BE+%D1%81%D1%87%D0%B0%D1%81%D1%82%D1%8C%D1%8F:289
Expected id of type track but found type %D0%9C%D1%8B+%D0%B2%D0%B5%D0%B7%D0%B5%D0%BC+%D1%82%D0%B5%D0%B1%D1%8F+%D0%B2+%D0%9C%D0%BE%D1%80%D0%B3 spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A1%D0%BC%D0%B5%D1%80%D1%82%D1%8C+%D0%90%D0%BC%D0%BE%D1%80%D0%B0%D0%BB%D0%B0.+Live+In+SayanCafe:%D0%9C%D1%8B+%D0%B2%D0%B5%D0%B7%D0%B5%D0%BC+%D1%82%D0%B5%D0%B1%D1%8F+%D0%B2+%D0%9C%D0%BE%D1%80%D0%B3:232
Expected id of type track but found type %D0%9A%D0%BB%D0%B0%D0%B4%D0%B1%D0%B8%D1%89%D0%B5%D0%BD%D1%81%D0%BA%D0%B0%D1%8F spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A1%D0%BC%D0%B5%D1%80%D1%82%D1%8C+%D0%90%D0%BC%D0%BE%D1%80%D0%B0%D0%BB%D0%B0.+Live+In+SayanCafe:%D0%9A%D0%BB%D0%B0%D0%B4%D0%B1%D0%B8%D1%89%D0%B5%D0%BD%D1%81%D0%BA%D0%B0%D1%8F:193
Expected id of type track but found type %D0%97%D0%B2%D0%B0%D0%BD%D1%8B%D0%B9+%D1%83%D0%B6%D0%B8%D0%BD spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A1%D0%BC%D0%B5%D1%80%D1%82%D1%8C+%D0%90%D0%BC%D0%BE%D1%80%D0%B0%D0%BB%D0%B0.+Live+In+SayanCafe:%D0%97%D0%B2%D0%B0%D0%BD%D1%8B%D0%B9+%D1%83%D0%B6%D0%B8%D0%BD:292
Expected id of type track but found type %D0%A2%D0%B0%D0%BD%D0%B3%D0%BE+%D0%BD%D0%B8%D1%87%D1%82%D0%BE%D0%B6%D0%B5%D1%81%D1%82%D0%B2 spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A1%D0%BC%D0%B5%D1%80%D1%82%D1%8C+%D0%90%D0%BC%D0%BE%D1%80%D0%B0%D0%BB%D0%B0.+Live+In+SayanCafe:%D0%A2%D0%B0%D0%BD%D0%B3%D0%BE+%D0%BD%D0%B8%D1%87%D1%82%D0%BE%D0%B6%D0%B5%D1%81%D1%82%D0%B2:287
Expected id of type track but found type %D0%A1%D0%BC%D0%B5%D1%80%D1%82%D1%8C+%D0%90%D0%BC%D0%BE%D1%80%D0%B0%D0%BB%D0%B0 spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A1%D0%BC%D0%B5%D1%80%D1%82%D1%8C+%D0%90%D0%BC%D0%BE%D1%80%D0%B0%D0%BB%D0%B0.+Live+In+SayanCafe:%D0%A1%D0%BC%D0%B5%D1%80%D1%82%D1%8C+%D0%90%D0%BC%D0%BE%D1%80%D0%B0%D0%BB%D0%B0:177
Expected id of type track but found type %D0%A3%D0%B1%D0%B5%D0%B9+%D0%A2%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21 spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A3%D0%B1%D0%B5%D0%B9+%D1%82%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21:%D0%A3%D0%B1%D0%B5%D0%B9+%D0%A2%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21:199
Expected id of type track but found type %D0%92%D1%81%D0%B5+%D0%BB%D1%8E%D0%B4%D0%B8%2C+%D1%81%D0%B2%D0%B0%D0%BB%D0%B8%D0%B2%D0%B0%D0%B9%D1%82%D0%B5+%D1%81+%D0%97%D0%B5%D0%BC%D0%BB%D0%B8%21 spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A3%D0%B1%D0%B5%D0%B9+%D1%82%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21:%D0%92%D1%81%D0%B5+%D0%BB%D1%8E%D0%B4%D0%B8%2C+%D1%81%D0%B2%D0%B0%D0%BB%D0%B8%D0%B2%D0%B0%D0%B9%D1%82%D0%B5+%D1%81+%D0%97%D0%B5%D0%BC%D0%BB%D0%B8%21:210
Expected id of type track but found type %D0%9F%D0%BE%D0%B6%D0%B0%D1%80+%D0%B2+%D0%BA%D1%83%D0%BA%D0%BE%D0%BB%D1%8C%D0%BD%D0%BE%D0%BC+%D1%82%D0%B5%D0%B0%D1%82%D1%80%D0%B5 spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A3%D0%B1%D0%B5%D0%B9+%D1%82%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21:%D0%9F%D0%BE%D0%B6%D0%B0%D1%80+%D0%B2+%D0%BA%D1%83%D0%BA%D0%BE%D0%BB%D1%8C%D0%BD%D0%BE%D0%BC+%D1%82%D0%B5%D0%B0%D1%82%D1%80%D0%B5:161
Expected id of type track but found type %D0%9F%D0%BE%D1%81%D0%BB%D0%B5%D0%B4%D0%BD%D0%B8%D0%B5+%D0%A1%D0%B5%D0%BA%D1%83%D0%BD%D0%B4%D1%8B+%D0%96%D0%B8%D0%B7%D0%BD%D0%B8 spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A3%D0%B1%D0%B5%D0%B9+%D1%82%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21:%D0%9F%D0%BE%D1%81%D0%BB%D0%B5%D0%B4%D0%BD%D0%B8%D0%B5+%D0%A1%D0%B5%D0%BA%D1%83%D0%BD%D0%B4%D1%8B+%D0%96%D0%B8%D0%B7%D0%BD%D0%B8:194
Expected id of type track but found type %D0%9E%D1%82%D0%B2%D1%80%D0%B0%D1%82%D0%B8%D0%BB%D0%BE%D0%B2%D0%BA%D0%B0 spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A3%D0%B1%D0%B5%D0%B9+%D1%82%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21:%D0%9E%D1%82%D0%B2%D1%80%D0%B0%D1%82%D0%B8%D0%BB%D0%BE%D0%B2%D0%BA%D0%B0:188
Expected id of type track but found type %D0%9C%D0%BE%D0%BB%D0%BE%D0%B4%D0%B8%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5+%D0%AF%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8 spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A3%D0%B1%D0%B5%D0%B9+%D1%82%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21:%D0%9C%D0%BE%D0%BB%D0%BE%D0%B4%D0%B8%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5+%D0%AF%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8:209
Expected id of type track but found type %D0%A3%D0%B3%D0%BE%D0%BD+%D0%A2%D1%80%D0%B0%D0%BC%D0%B2%D0%B0%D1%8F spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A3%D0%B1%D0%B5%D0%B9+%D1%82%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21:%D0%A3%D0%B3%D0%BE%D0%BD+%D0%A2%D1%80%D0%B0%D0%BC%D0%B2%D0%B0%D1%8F:278
Expected id of type track but found type %D0%9F%D0%BE%D0%BB%D0%B8%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9+%D0%9F%D0%B8%D0%B4%D0%BE%D1%80 spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A3%D0%B1%D0%B5%D0%B9+%D1%82%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21:%D0%9F%D0%BE%D0%BB%D0%B8%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9+%D0%9F%D0%B8%D0%B4%D0%BE%D1%80:137
Expected id of type track but found type %D0%9F%D0%BB%D0%BE%D0%B4%D1%8B+%D0%94%D0%B5%D1%82%D1%81%D1%82%D0%B2%D0%B0+%D0%A1%D1%82%D0%B0%D1%80%D0%B8%D0%BA%D0%B8 spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A3%D0%B1%D0%B5%D0%B9+%D1%82%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21:%D0%9F%D0%BB%D0%BE%D0%B4%D1%8B+%D0%94%D0%B5%D1%82%D1%81%D1%82%D0%B2%D0%B0+%D0%A1%D1%82%D0%B0%D1%80%D0%B8%D0%BA%D0%B8:217
Expected id of type track but found type %D0%A1%D0%BF%D1%80%D0%BE%D1%81%D0%B8+%D1%83+%D0%BC%D0%B5%D1%80%D1%82%D0%B2%D0%BE%D0%B3%D0%BE+%D0%97%D0%B4%D0%BE%D1%80%D0%BE%D0%B2%D1%8C%D1%8F spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A3%D0%B1%D0%B5%D0%B9+%D1%82%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21:%D0%A1%D0%BF%D1%80%D0%BE%D1%81%D0%B8+%D1%83+%D0%BC%D0%B5%D1%80%D1%82%D0%B2%D0%BE%D0%B3%D0%BE+%D0%97%D0%B4%D0%BE%D1%80%D0%BE%D0%B2%D1%8C%D1%8F:206
Expected id of type track but found type %D0%A3%D0%B1%D0%B5%D0%B9+%D0%A2%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21 spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A3%D0%B1%D0%B5%D0%B9+%D0%A2%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21+Live+In+SayanCafe:%D0%A3%D0%B1%D0%B5%D0%B9+%D0%A2%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21:195
Expected id of type track but found type %D0%92%D1%81%D0%B5+%D0%BB%D1%8E%D0%B4%D0%B8%2C+%D1%81%D0%B2%D0%B0%D0%BB%D0%B8%D0%B2%D0%B0%D0%B9%D1%82%D0%B5+%D1%81+%D0%97%D0%B5%D0%BC%D0%BB%D0%B8%21 spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A3%D0%B1%D0%B5%D0%B9+%D0%A2%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21+Live+In+SayanCafe:%D0%92%D1%81%D0%B5+%D0%BB%D1%8E%D0%B4%D0%B8%2C+%D1%81%D0%B2%D0%B0%D0%BB%D0%B8%D0%B2%D0%B0%D0%B9%D1%82%D0%B5+%D1%81+%D0%97%D0%B5%D0%BC%D0%BB%D0%B8%21:180
Expected id of type track but found type %D0%9F%D0%BE%D0%B6%D0%B0%D1%80+%D0%B2+%D0%BA%D1%83%D0%BA%D0%BE%D0%BB%D1%8C%D0%BD%D0%BE%D0%BC+%D1%82%D0%B5%D0%B0%D1%82%D1%80%D0%B5 spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A3%D0%B1%D0%B5%D0%B9+%D0%A2%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21+Live+In+SayanCafe:%D0%9F%D0%BE%D0%B6%D0%B0%D1%80+%D0%B2+%D0%BA%D1%83%D0%BA%D0%BE%D0%BB%D1%8C%D0%BD%D0%BE%D0%BC+%D1%82%D0%B5%D0%B0%D1%82%D1%80%D0%B5:143
Expected id of type track but found type %D0%9F%D0%BE%D1%81%D0%BB%D0%B5%D0%B4%D0%BD%D0%B8%D0%B5+%D0%A1%D0%B5%D0%BA%D1%83%D0%BD%D0%B4%D1%8B+%D0%96%D0%B8%D0%B7%D0%BD%D0%B8 spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A3%D0%B1%D0%B5%D0%B9+%D0%A2%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21+Live+In+SayanCafe:%D0%9F%D0%BE%D1%81%D0%BB%D0%B5%D0%B4%D0%BD%D0%B8%D0%B5+%D0%A1%D0%B5%D0%BA%D1%83%D0%BD%D0%B4%D1%8B+%D0%96%D0%B8%D0%B7%D0%BD%D0%B8:183
Expected id of type track but found type %D0%9E%D1%82%D0%B2%D1%80%D0%B0%D1%82%D0%B8%D0%BB%D0%BE%D0%B2%D0%BA%D0%B0 spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A3%D0%B1%D0%B5%D0%B9+%D0%A2%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21+Live+In+SayanCafe:%D0%9E%D1%82%D0%B2%D1%80%D0%B0%D1%82%D0%B8%D0%BB%D0%BE%D0%B2%D0%BA%D0%B0:189
Expected id of type track but found type %D0%9C%D0%BE%D0%BB%D0%BE%D0%B4%D0%B8%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5+%D0%AF%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8 spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A3%D0%B1%D0%B5%D0%B9+%D0%A2%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21+Live+In+SayanCafe:%D0%9C%D0%BE%D0%BB%D0%BE%D0%B4%D0%B8%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5+%D0%AF%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8:244
Expected id of type track but found type %D0%A3%D0%B3%D0%BE%D0%BD%D1%89%D0%B8%D0%BA+%D0%A2%D1%80%D0%B0%D0%BC%D0%B2%D0%B0%D1%8F spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A3%D0%B1%D0%B5%D0%B9+%D0%A2%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21+Live+In+SayanCafe:%D0%A3%D0%B3%D0%BE%D0%BD%D1%89%D0%B8%D0%BA+%D0%A2%D1%80%D0%B0%D0%BC%D0%B2%D0%B0%D1%8F:301
Expected id of type track but found type %D0%96%D0%B0%D0%BB%D0%BA%D0%B0%D1%8F+%D0%A1%D0%BE%D0%B1%D0%B0%D1%87%D0%BE%D0%BD%D0%BA%D0%B0 spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A3%D0%B1%D0%B5%D0%B9+%D0%A2%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21+Live+In+SayanCafe:%D0%96%D0%B0%D0%BB%D0%BA%D0%B0%D1%8F+%D0%A1%D0%BE%D0%B1%D0%B0%D1%87%D0%BE%D0%BD%D0%BA%D0%B0:229
Expected id of type track but found type %D0%9F%D0%BE%D0%BB%D0%B8%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9+%D0%9F%D0%B8%D0%B4%D0%BE%D1%80 spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A3%D0%B1%D0%B5%D0%B9+%D0%A2%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21+Live+In+SayanCafe:%D0%9F%D0%BE%D0%BB%D0%B8%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9+%D0%9F%D0%B8%D0%B4%D0%BE%D1%80:130
Expected id of type track but found type %D0%9F%D0%BB%D0%BE%D0%B4%D1%8B+%D0%94%D0%B5%D1%82%D1%81%D1%82%D0%B2%D0%B0+%D0%A1%D1%82%D0%B0%D1%80%D0%B8%D0%BA%D0%B8 spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A3%D0%B1%D0%B5%D0%B9+%D0%A2%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21+Live+In+SayanCafe:%D0%9F%D0%BB%D0%BE%D0%B4%D1%8B+%D0%94%D0%B5%D1%82%D1%81%D1%82%D0%B2%D0%B0+%D0%A1%D1%82%D0%B0%D1%80%D0%B8%D0%BA%D0%B8:197
Expected id of type track but found type %D0%A1%D0%BF%D1%80%D0%BE%D1%81%D0%B8+%D1%83+%D0%BC%D0%B5%D1%80%D1%82%D0%B2%D0%BE%D0%B3%D0%BE+%D0%97%D0%B4%D0%BE%D1%80%D0%BE%D0%B2%D1%8C%D1%8F spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A3%D0%B1%D0%B5%D0%B9+%D0%A2%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21+Live+In+SayanCafe:%D0%A1%D0%BF%D1%80%D0%BE%D1%81%D0%B8+%D1%83+%D0%BC%D0%B5%D1%80%D1%82%D0%B2%D0%BE%D0%B3%D0%BE+%D0%97%D0%B4%D0%BE%D1%80%D0%BE%D0%B2%D1%8C%D1%8F:303
Expected id of type track but found type %D0%97%D0%B2%D0%B5%D1%80%D0%B7%D0%BE%D1%81%D1%82%D1%8C spotify:local:%D0%9E%D1%80%D0%B3%D0%B0%D0%B7%D0%BC+%D0%9D%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BC%D1%83%D1%81%D0%B0:%D0%A3%D0%B1%D0%B5%D0%B9+%D0%A2%D0%B8%D0%BD%D0%B5%D0%B9%D0%B4%D0%B6%D0%B5%D1%80%D0%B0%21+Live+In+SayanCafe:%D0%97%D0%B2%D0%B5%D1%80%D0%B7%D0%BE%D1%81%D1%82%D1%8C:247
HTTP Error for POST to https://api.spotify.com/v1/playlists/3PrVYE5UPJYkEzWxe7rwPF/tracks with Params: {'position': None} returned 400 due to Invalid track uri: spotify:track:211
Traceback (most recent call last):
  File "D:\AppData\Roaming\Python\Python310\site-packages\spotipy\client.py", line 245, in _internal_call
    response.raise_for_status()
  File "C:\Program Files\Python310\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.spotify.com/v1/playlists/3PrVYE5UPJYkEzWxe7rwPF/tracks

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Desktop\spotibot\main.py", line 28, in <module>
    spoti_utils.add_tracks_to_playlist(sp, "3PrVYE5UPJYkEzWxe7rwPF", tracks)
  File "E:\Desktop\spotibot\spoti_utils.py", line 23, in add_tracks_to_playlist
    sp.playlist_add_items(playlist_id, tracks[i:i + 100])
  File "D:\AppData\Roaming\Python\Python310\site-packages\spotipy\client.py", line 1031, in playlist_add_items
    return self._post(
  File "D:\AppData\Roaming\Python\Python310\site-packages\spotipy\client.py", line 302, in _post
    return self._internal_call("POST", url, payload, kwargs)
  File "D:\AppData\Roaming\Python\Python310\site-packages\spotipy\client.py", line 267, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 400, code:-1 - https://api.spotify.com/v1/playlists/3PrVYE5UPJYkEzWxe7rwPF/tracks:
 Invalid track uri: spotify:track:211, reason: None

Process finished with exit code 1
```

**Comment by Peter-Schorn** [comment]
It's not possible to add a local track to a playlist using the web API. See [here](https://developer.spotify.com/documentation/general/guides/local-files-spotify-playlists/).
