### ISSUE TITLE
Using Flask, RuntimeError: Working outside of request context.

### ISSUE THREAD

**Issue by Andrew3212** [spotipy-dev/spotipy#924]
Trying to allow other people to get their current playing song with a Discord bot
Tried using this flask example below
https://github.com/spotipy-dev/spotipy/blob/master/examples/app.py

this is my code

```
@bot.command
@lightbulb.command('c', 'Current Song')
@lightbulb.implements(lightbulb.PrefixCommand)
@app.route('/currently_playing')
async def currently_playing(ctx):
    cache_handler = spotipy.cache_handler.FlaskSessionCacheHandler(session)
    auth_manager = spotipy.oauth2.SpotifyOAuth(scope='user-read-currently-playing', cache_handler=cache_handler)
    if not auth_manager.validate_token(cache_handler.get_cached_token()):
        return redirect('/')
    sp = spotipy.Spotify(auth_manager=auth_manager)       
    song = sp.current_user_playing_track()
```

but i keep getting this error

```
raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request. Consult the documentation on testing for
information about how to avoid this problem.
```

**Comment by stephanebruckert** [comment]
Do you know at what line is the error raised? This might be flask-related, not spotipy

**Comment by Andrew3212** [comment]
`if not auth_manager.validate_token(cache_handler.get_cached_token()):`
I've never used flask before so i'm not sure whats wrong.

**Comment by stephanebruckert** [comment]
Would you have a complete stack trace?

**Comment by Andrew3212** [comment]
```
Traceback (most recent call last):
  File "C:\Users\arg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\lightbulb\app.py", line 1038, in handle_message_create_for_prefix_commands
    await self.process_prefix_commands(context)
  File "C:\Users\arg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\lightbulb\app.py", line 1010, in process_prefix_commands
    await context.invoke()
  File "C:\Users\arg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\lightbulb\context\base.py", line 311, in invoke
    await self.command.invoke(self)
  File "C:\Users\arg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\lightbulb\commands\prefix.py", line 119, in invoke
    await self(context, **kwargs)
  File "C:\Users\arg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\lightbulb\commands\base.py", line 605, in __call__
    return await self.callback(context, **kwargs)
  File "C:\Users\arg\OneDrive\Documents\DiscordBotProject\bot.py", line 142, in currently_playing
    if not auth_manager.validate_token(cache_handler.get_cached_token()):
  File "C:\Users\arg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\spotipy\cache_handler.py", line 163, in get_cached_token
    token_info = self.session["token_info"]
  File "C:\Users\arg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\werkzeug\local.py", line 316, in __get__
    obj = instance._get_current_object()  # type: ignore[misc]
  File "C:\Users\arg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of request context.
```

**Comment by stephanebruckert** [comment]
Okay I'm not sure to be honest.

Have you tried running the example as it is in https://github.com/spotipy-dev/spotipy/blob/master/examples/app.py and does it work? I've just tried it again and it works for me.

I don't know your full code, what steps you took and whether the lines you added have an impact:

    @bot.command
    @lightbulb.command('c', 'Current Song')
    @lightbulb.implements(lightbulb.PrefixCommand)

**Comment by Andrew3212** [comment]
I figured it out. Had to run flask on a different thread and had to switch ports as well.
Sorry about that, and thanks.
`def flaskfrog():
    if __name__ == '__name__':
        app.run(5000, use_reloader=False)
    app.run(port=5000, use_reloader=False)

t_flask = threading.Thread(target=flaskfrog)
t_flask.start()`
