### ISSUE TITLE
playlist_add_items not working

### ISSUE THREAD

**Issue by DeepVasoya08** [spotipy-dev/spotipy#931]
**Describe the bug**
playlist_add_items () is broken it is throwing error

**Your code**
`try:
    self.spotify.playlist_add_items(playlist_id, song_uri)
    return True
except spotipy.SpotifyException as e:
    raise Exception(e)`

**while this line is perfectly working -> url = (f"https://api.spotify.com/v1/playlists/{playlist_id}/tracks?uris={song_uri}")**

**Expected behavior**
song should be added to playlist

**Output**
Exception: http status: 400, code:-1 - https://api.spotify.com/v1/playlists/1LMi4K1NtYWRUkU2kKjJQo/tracks:
 Invalid track uri: spotify:track:s, reason: None

**Environment:**
 - OS: [Windows]
 - Python version [3.10.9]
 - spotipy version [2.22.0]

**Comment by DeepVasoya08** [comment]
> It looks like your variable `song_uri` is simply `"spotify:track:s"`, could you check?

Yes i checked twice both song uri and playlist uri

**Comment by DeepVasoya08** [comment]
> It looks like your variable `song_uri` is simply `"spotify:track:s"`, could you check?

Yes i checked twice, both song uri and playlist uri

**Comment by stephanebruckert** [comment]
Please provide a minimal reproducible example and print `song_uri` for us.

**Comment by DeepVasoya08** [comment]
> Please provide a minimal reproducible example and print `song_uri` for us.

here is full output of the code:

song_uri--------> spotify:track:2VGs7EmaIxq96Wcog6DQOc
playlist_id------> 77VRlvcF6Qm5BFHfCjauaj

HTTP Error for POST to https://api.spotify.com/v1/playlists/77VRlvcF6Qm5BFHfCjauaj/tracks with Params: {'position': None} returned 400 due to Invalid track uri: spotify:track:s
Traceback (most recent call last):
  File "C:\Users\deepv\.virtualenvs\only_music-SaPE63u8\lib\site-packages\spotipy\client.py", line 245, in _internal_call
    response.raise_for_status()
  File "C:\Users\deepv\.virtualenvs\only_music-SaPE63u8\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.spotify.com/v1/playlists/77VRlvcF6Qm5BFHfCjauaj/tracks
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\projects\only_music\spotify_client.py", line 80, in add_song
    self.spotify.playlist_add_items(playlist_id, song_uri)
  File "C:\Users\deepv\.virtualenvs\only_music-SaPE63u8\lib\site-packages\spotipy\client.py", line 1040, in playlist_add_items
    return self._post(
  File "C:\Users\deepv\.virtualenvs\only_music-SaPE63u8\lib\site-packages\spotipy\client.py", line 302, in _post
    return self._internal_call("POST", url, payload, kwargs)
  File "C:\Users\deepv\.virtualenvs\only_music-SaPE63u8\lib\site-packages\spotipy\client.py", line 267, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 400, code:-1 - https://api.spotify.com/v1/playlists/77VRlvcF6Qm5BFHfCjauaj/tracks:    
 Invalid track uri: spotify:track:s, reason: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\projects\only_music\main.py", line 106, in <module>
    main()
  File "d:\projects\only_music\main.py", line 100, in main
    add_song = spotify_client.add_song(song_uri, playlist["id"])
  File "d:\projects\only_music\spotify_client.py", line 83, in add_song
    raise Exception(e)
Exception: http status: 400, code:-1 - https://api.spotify.com/v1/playlists/77VRlvcF6Qm5BFHfCjauaj/tracks:
 Invalid track uri: spotify:track:s, reason: None

**Comment by DeepVasoya08** [comment]
> Please provide a minimal reproducible example and print `song_uri` for us.

here is full output of the code:

song_uri--------> spotify:track:2VGs7EmaIxq96Wcog6DQOc
playlist_id------> 77VRlvcF6Qm5BFHfCjauaj

HTTP Error for POST to https://api.spotify.com/v1/playlists/77VRlvcF6Qm5BFHfCjauaj/tracks with Params: {'position': None} returned 400 due to Invalid track uri: spotify:track:s

Traceback (most recent call last):
File "C:\Users\deepv.virtualenvs\only_music-SaPE63u8\lib\site-packages\spotipy\client.py", line 245, in _internal_call
response.raise_for_status()
File "C:\Users\deepv.virtualenvs\only_music-SaPE63u8\lib\site-packages\requests\models.py", line 1021, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.spotify.com/v1/playlists/77VRlvcF6Qm5BFHfCjauaj/tracks

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "d:\projects\only_music\spotify_client.py", line 80, in add_song
self.spotify.playlist_add_items(playlist_id, song_uri)
File "C:\Users\deepv.virtualenvs\only_music-SaPE63u8\lib\site-packages\spotipy\client.py", line 1040, in playlist_add_items
return self._post(
File "C:\Users\deepv.virtualenvs\only_music-SaPE63u8\lib\site-packages\spotipy\client.py", line 302, in _post
return self._internal_call("POST", url, payload, kwargs)
File "C:\Users\deepv.virtualenvs\only_music-SaPE63u8\lib\site-packages\spotipy\client.py", line 267, in _internal_call
raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 400, code:-1 - https://api.spotify.com/v1/playlists/77VRlvcF6Qm5BFHfCjauaj/tracks:
Invalid track uri: spotify:track:s, reason: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "d:\projects\only_music\main.py", line 106, in
main()
File "d:\projects\only_music\main.py", line 100, in main
add_song = spotify_client.add_song(song_uri, playlist["id"])
File "d:\projects\only_music\spotify_client.py", line 83, in add_song
raise Exception(e)
Exception: http status: 400, code:-1 - https://api.spotify.com/v1/playlists/77VRlvcF6Qm5BFHfCjauaj/tracks:
Invalid track uri: spotify:track:s, reason: None

**Comment by DeepVasoya08** [comment]
> OK according to https://spotipy.readthedocs.io/en/2.22.0/#spotipy.client.Spotify.playlist_add_items, `items` needs to be a list.
> 
> So use `playlist_add_items(playlist_id, [song_uri])` instead of `playlist_add_items(playlist_id, song_uri)`

nice catch👍

Thank you!
